### ISSUE TITLE
pretrain.py无法运行

### ISSUE THREAD

**Issue by preordinary** [changruijie/simple_LLM_pretrain_learning_model#3]
作者好！我按照以下步骤运行项目：（单卡20gb）
1. python data_process.py 
结果：没有报错，生成了bin文件。

2. python pretrain.py（并且更改了torch的sampler）
结果：
```
Traceback (most recent call last):
  File "/root/yyz_repo/simple_LLM_pretrain_learning_model/pretrain.py", line 323, in <module>
    train_epoch(epoch)
  File "/root/yyz_repo/simple_LLM_pretrain_learning_model/pretrain.py", line 71, in train_epoch
    logits = model(X, Y)
  File "/root/.conda/envs/internlm-demo/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/yyz_repo/simple_LLM_pretrain_learning_model/model.py", line 280, in forward
    h = self.tok_embeddings(tokens)
  File "/root/.conda/envs/internlm-demo/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.conda/envs/internlm-demo/lib/python3.10/site-packages/torch/nn/modules/sparse.py", line 162, in forward
    return F.embedding(
  File "/root/.conda/envs/internlm-demo/lib/python3.10/site-packages/torch/nn/functional.py", line 2210, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: CUDA error: device-side assert triggered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```
我搜索了一下，感觉是数组越界了，cuda debug显示：`Assertion srcIndex < srcSelectDimSize`failed.
请问能帮忙检查一下嘛？

还有如果readme中能有使用步骤的说明就更好了。
感谢作者！

**Comment by preordinary** [comment]
放到cpu执行后，提示了更详细的报错：
```
Traceback (most recent call last):
  File "/root/yyz_repo/simple_LLM_pretrain_learning_model/pretrain.py", line 324, in <module>
    train_epoch(epoch)
  File "/root/yyz_repo/simple_LLM_pretrain_learning_model/pretrain.py", line 71, in train_epoch
    logits = model(X, Y)
  File "/root/.conda/envs/internlm-demo/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/yyz_repo/simple_LLM_pretrain_learning_model/model.py", line 280, in forward
    h = self.tok_embeddings(tokens)
  File "/root/.conda/envs/internlm-demo/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.conda/envs/internlm-demo/lib/python3.10/site-packages/torch/nn/modules/sparse.py", line 162, in forward
    return F.embedding(
  File "/root/.conda/envs/internlm-demo/lib/python3.10/site-packages/torch/nn/functional.py", line 2210, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
IndexError: index out of range in self
```
应该是token embedding的时候有问题，麻烦作者排查一下。感谢！
